const mineflayer=require('mineflayer')
const {pathfinder,Movements,goals}=require('mineflayer-pathfinder')
const minecraftData=require('minecraft-data')
const fs=require('fs'),vm=require('vm')
const CFG={host:process.env.MC_HOST||'funvanillaworld.aternos.me',port:Number(process.env.MC_PORT||57004),username:process.env.MC_USERNAME||'Bot_Vanilla',version:process.env.MC_VERSION||'1.21.11',ollama:process.env.OLLAMA_URL||'http://127.0.0.1:11434/api/generate',model:process.env.OLLAMA_MODEL||'llama3:latest',memory:process.env.MEMORY_FILE||'./memory.json',aiTimeout:Number(process.env.AI_TIMEOUT||120000)}
const wait=ms=>new Promise(r=>setTimeout(r,ms))
const OPEN=new Set(['air','cave_air','void_air','water','lava','short_grass','tall_grass','fern','large_fern','snow','vine','glow_lichen'])
const ORE={coal_ore:['coal_ore','deepslate_coal_ore'],iron_ore:['iron_ore','deepslate_iron_ore'],copper_ore:['copper_ore','deepslate_copper_ore'],gold_ore:['gold_ore','deepslate_gold_ore'],redstone_ore:['redstone_ore','deepslate_redstone_ore'],lapis_ore:['lapis_ore','deepslate_lapis_ore'],diamond_ore:['diamond_ore','deepslate_diamond_ore'],emerald_ore:['emerald_ore','deepslate_emerald_ore']}
const ALIAS={log:['oak_log','birch_log','spruce_log','jungle_log','acacia_log','dark_oak_log','mangrove_log','cherry_log'],wood:['oak_log','birch_log','spruce_log','jungle_log','acacia_log','dark_oak_log','mangrove_log','cherry_log'],stone:['stone','cobblestone','deepslate'],dirt:['dirt','grass_block','coarse_dirt','rooted_dirt'],sand:['sand','red_sand']}
const BLOCKED=/\b(require|import|export|process|child_process|fs|fetch|axios|http|https|net|tls|dgram|worker_threads|eval|Function|WebAssembly|Buffer|global|globalThis)\b/i
class Agent{
constructor(bot){this.bot=bot;this.task=0;this.busy=false;this.last='';this.lastAt=0;this.memory=this.load();this.tools=this.loadTools();this.toolDepth=0}
load(){try{const x=JSON.parse(fs.readFileSync(CFG.memory,'utf8'));return x&&typeof x==='object'?x:{history:[],tools:{}}}catch(_){return{history:[],tools:{}}}}
save(){try{this.memory.tools=this.tools;fs.writeFileSync(CFG.memory,JSON.stringify(this.memory,null,2))}catch(e){console.log('[MEMORY]',e.message)}}
validName(n){return/^[A-Za-z_$][\w$]{0,48}$/.test(String(n||''))}
validateToolSource(s){s=String(s||'').trim();if(!s||s.length>9000||BLOCKED.test(s))return false;try{const f=new vm.Script(`(${s})`).runInNewContext({Math,JSON,Date},{timeout:1000});return typeof f==='function'}catch(_){return false}}
loadTools(){const src=this.memory.tools&&typeof this.memory.tools==='object'?this.memory.tools:{};const out={};for(const[n,s]of Object.entries(src))if(this.validName(n)&&this.validateToolSource(s))out[n]=String(s);return out}
async installTool(n,s){n=String(n||'').trim();s=String(s||'').trim();if(!this.validName(n))throw Error('недопустимое имя инструмента: '+n);if(!this.validateToolSource(s))throw Error('инструмент '+n+' отклонён: неверный или небезопасный код');this.tools[n]=s;this.save();console.log('[TOOL] установлен:',n);return true}
say(t){t=String(t??'').replace(/\s+/g,' ').trim().slice(0,240);if(!t)return;const n=Date.now();if(t===this.last&&n-this.lastAt<8000)return;this.last=t;this.lastAt=n;this.bot.chat(t)}
position(){const p=this.bot.entity?.position;return p?{x:Math.round(p.x),y:Math.round(p.y),z:Math.round(p.z)}:null}
players(){return Object.values(this.bot.players||{}).filter(p=>p.username&&p.username!==this.bot.username).map(p=>({name:p.username,position:p.entity?{x:Math.round(p.entity.position.x),y:Math.round(p.entity.position.y),z:Math.round(p.entity.position.z)}:null}))}
world(){return{position:this.position(),health:this.bot.health,food:this.bot.food,dimension:this.bot.game?.dimension,players:this.players().slice(0,16),inventory:this.bot.inventory.items().map(i=>({name:i.name,count:i.count}))}}
blockAt(x,y,z){const b=this.bot.blockAt({x:Number(x),y:Number(y),z:Number(z)});return b?{name:b.name,type:b.type,x:b.position.x,y:b.position.y,z:b.position.z,hardness:b.hardness,boundingBox:b.boundingBox}:null}
matches(b,n){n=String(n||'').toLowerCase();return!!b&&(ALIAS[n]||ORE[n]||[n]).includes(b.name)}
findBlocks(n,d=32,c=100){const out=[];try{const ps=this.bot.findBlocks({maxDistance:Math.max(1,Number(d)||32),count:Math.min(200,Math.max(1,Number(c)||100)),matching:b=>this.matches(b,n)});for(const p of ps){const b=this.bot.blockAt(p);if(b)out.push({name:b.name,type:b.type,x:b.position.x,y:b.position.y,z:b.position.z})}}catch(e){console.log('[FIND_BLOCKS]',e.message)}return out}
findBlock(n,d=32){return this.findBlocks(n,d,1)[0]||null}
findVisible(n,d=32){return this.findBlocks(n,d,100).find(p=>[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]].some(v=>{const b=this.bot.blockAt({x:p.x+v[0],y:p.y+v[1],z:p.z+v[2]});return!b||OPEN.has(b.name)||b.boundingBox==='empty'}))||null}
async goTo(p,id=this.task,timeout=20000){this.bot.pathfinder.setGoal(new goals.GoalNear(Number(p.x),Number(p.y),Number(p.z),2));const t=Date.now();while(Date.now()-t<timeout){if(id!==this.task)return false;if(this.bot.entity?.position.distanceTo(p)<=3.5){this.bot.pathfinder.setGoal(null);return true}await wait(200)}this.bot.pathfinder.setGoal(null);return false}
count(n){n=String(n||'');let r;if(n==='log'||n==='wood')r=/_log$/;else if(n==='stone')r=/^(stone|cobblestone|deepslate)$/;else if(n==='diamond_ore')r=/^diamond$/;else if(n==='iron_ore')r=/^(raw_iron|iron_ingot)$/;else r=new RegExp('^'+n.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'$');return this.bot.inventory.items().filter(i=>r.test(i.name)).reduce((s,i)=>s+i.count,0)}
async tool(n){let type=null;if(/log|wood|planks/.test(n))type='axe';else if(/dirt|sand|gravel|clay/.test(n))type='shovel';else if(/ore|stone|cobblestone|deepslate|netherrack|end_stone/.test(n))type='pickaxe';if(!type)return;const i=this.bot.inventory.items().find(x=>x.name.endsWith('_'+type));if(i)await this.bot.equip(i,'hand')}
async mine(n,c=1){if(this.busy)throw Error('бот занят');this.busy=true;const id=++this.task;let got=0;try{for(let k=0;k<100&&got<c&&id===this.task;k++){const b=this.findVisible(n);if(!b){await this.exploreStep(id);continue}if(!await this.goTo(b,id))continue;const before=this.count(n);await this.tool(b.name);const real=this.bot.blockAt({x:b.x,y:b.y,z:b.z});if(real)try{await this.bot.lookAt(real.position.offset(.5,.5,.5),true);await this.bot.dig(real,true)}catch(e){console.log('[DIG]',e.message)}await wait(250);got+=Math.max(0,this.count(n)-before)}return got}finally{if(id===this.task)this.busy=false}}
async exploreStep(id=this.task){const p=this.bot.entity.position,a=Math.random()*Math.PI*2;return this.goTo({x:p.x+Math.cos(a)*12,y:p.y,z:p.z+Math.sin(a)*12},id,7000)}
async collect(n,c=1){const now=this.count(n);if(now>=c)return now;await this.mine(n,c-now);return this.count(n)}
async craft(n,c=1){const data=minecraftData(this.bot.version),item=data.itemsByName[n];if(!item)throw Error('неизвестный предмет: '+n);let table=null,recipe=this.bot.recipesFor(item.id,null,c,null)[0];if(!recipe){table=this.bot.findBlock({matching:b=>b?.name==='crafting_table',maxDistance:32});if(table){await this.goTo(table.position,this.task,15000);recipe=this.bot.recipesFor(item.id,null,c,table)[0]}}if(!recipe)throw Error('нет доступного рецепта для '+n);await this.bot.craft(recipe,c,table||null);return this.count(n)}
async equip(n,d='hand'){const i=this.bot.inventory.items().find(x=>x.name===n);if(!i)throw Error('предмет не найден: '+n);await this.bot.equip(i,d);return i.name}
async breakBlock(x,y,z){const b=this.bot.blockAt({x:Number(x),y:Number(y),z:Number(z)});if(!b||OPEN.has(b.name))throw Error('блок не найден');await this.goTo(b.position,this.task,12000);await this.tool(b.name);await this.bot.lookAt(b.position.offset(.5,.5,.5),true);await this.bot.dig(b,true);return true}
async place(n,dx=0,dy=0,dz=0){const i=this.bot.inventory.items().find(x=>x.name===n);if(!i)throw Error('блок не найден: '+n);const p=this.bot.entity.position.offset(Number(dx),Number(dy),Number(dz));const ref=this.bot.blockAt(p.offset(0,-1,0));if(!ref||ref.boundingBox!=='block')throw Error('нет поверхности');await this.goTo(ref.position,this.task,10000);await this.bot.equip(i,'hand');await this.bot.placeBlock(ref,{x:0,y:1,z:0});return true}
async attack(n){const p=this.bot.players[n]?.entity;if(!p)throw Error('игрок не найден или не виден');this.task++;for(let i=0;i<8&&p.isValid;i++){if(this.bot.entity.position.distanceTo(p.position)>3)await this.goTo(p.position,this.task,5000);await this.bot.lookAt(p.position.offset(0,1,0),true);this.bot.attack(p);await wait(500)}return true}
async follow(n){const p=this.bot.players[n]?.entity;if(!p)return false;this.task++;this.bot.pathfinder.setGoal(new goals.GoalFollow(p,2),true);return true}
stop(){this.task++;this.busy=false;this.bot.pathfinder.setGoal(null);this.bot.clearControlStates()}
async callTool(n,args,user){if(!this.tools[n])throw Error('MISSING_TOOL:'+n);if(this.toolDepth>=4)throw Error('слишком глубокий вызов инструментов');this.toolDepth++;try{const api=this.api(user),fn=new vm.Script(`(${this.tools[n]})`).runInNewContext({mc:api,Math,JSON,Date,console:{log:(...x)=>console.log('[TOOL '+n+']',...x)}},{timeout:3000});if(typeof fn!=='function')throw Error('инструмент не является функцией');return await Promise.race([Promise.resolve(fn(api,args||{})),new Promise((_,r)=>setTimeout(()=>r(Error('таймаут инструмента '+n)),30000))])}finally{this.toolDepth--}}
api(user){const api={say:t=>this.say(t),chat:t=>this.say(t),sleep:wait,world:()=>this.world(),inspect:()=>this.world(),players:()=>this.players(),position:()=>this.position(),getPosition:()=>this.position(),blockAt:(x,y,z)=>this.blockAt(x,y,z),findBlock:(n,d)=>this.findBlock(n,d),findBlocks:(n,d,c)=>this.findBlocks(n,d,c),findVisible:(n,d)=>this.findVisible(n,d),findVisibleBlocks:(n,d,c)=>this.findBlocks(n,d,c),goTo:(x,y,z)=>this.goTo({x:Number(x),y:Number(y),z:Number(z)}),mine:(n,c)=>this.mine(n,c),collect:(n,c)=>this.collect(n,c),craft:(n,c)=>this.craft(n,c),equip:(n,d)=>this.equip(n,d),place:(n,x,y,z)=>this.place(n,x,y,z),placeCraftingTable:()=>this.place('crafting_table',0,0,1),breakBlock:(x,y,z)=>this.breakBlock(x,y,z),attack:n=>this.attack(n),follow:()=>this.follow(user),explore:()=>this.exploreStep(),jump:async()=>{this.bot.setControlState('jump',true);await wait(150);this.bot.setControlState('jump',false)},stop:async()=>this.stop(),lookAt:(x,y,z)=>this.bot.lookAt({x:Number(x),y:Number(y),z:Number(z)},true),inventory:()=>this.bot.inventory.items().map(i=>({name:i.name,count:i.count,slot:i.slot})),count:n=>this.count(n)};for(const n of this.toolNames())api[n]=(args={})=>this.callTool(n,args,user);return api}
toolNames(){return Object.keys(this.tools)}
clean(s){return String(s||'').replace(/^```(?:js|javascript)?\s*/i,'').replace(/\s*```$/i,'').trim()}
safe(s){return s.length<=12000&&!BLOCKED.test(s)}
async run(code,user){code=this.clean(code);if(!code)return{ok:false,error:'AI не вернул код'};if(!this.safe(code))return{ok:false,error:'код содержит запрещённые возможности'};const base=this.api(user),mc=new Proxy(base,{get(t,p){if(typeof p==='string'&&!(p in t))throw Error('MISSING_TOOL:'+p);return t[p]}});try{const s=new vm.Script(`(async()=>{\n${code}\n})()`);return{ok:true,result:await Promise.race([s.runInNewContext({mc,Math,JSON,Date,console:{log:(...x)=>console.log('[AI]',...x)}},{timeout:5000}),new Promise((_,r)=>setTimeout(()=>r(Error('таймаут действия')),60000))])}}catch(e){const m=String(e.message||e),x=m.match(/MISSING_TOOL:([A-Za-z_$][\w$]*)/);return{ok:false,error:m,missingTool:x?.[1]||null}}}
async ai(user,msg,extra=''){const history=(this.memory.history||[]).slice(-10).map(x=>`${x.user}: ${x.message}`).join('\n');const prompt=`Ты автономный Minecraft AI-агент. Если запрос является вопросом, разговором, объяснением или просьбой ответить текстом: type=text, code="", tools=[]. Если пользователь просит выполнить действие в Minecraft: type=action и code=JavaScript через mc API. say всегда только обычный человеческий текст, никогда JavaScript. Если для действия нет нужной функции, создай её в tools. Формат инструмента: async (mc,args)=>{...}; использовать можно только mc API. После установки инструмент сохраняется в memory.json и вызывается как mc.имя(args). Не используй bot, require, import, process, fs, fetch, eval, Function, сеть или скрытые координаты. Для поиска блоков используй mc.findBlocks(name,distance,count) или mc.findBlock(name,distance). Верни ТОЛЬКО JSON: {"type":"text|action","say":"текст","code":"код или пусто","tools":[{"name":"имя","source":"async (mc,args)=>{...}"}]}. Для text code и tools пустые. API: mc.say,mc.chat,mc.sleep,mc.world,mc.inspect,mc.players,mc.position,mc.getPosition,mc.blockAt,mc.findBlock,mc.findBlocks,mc.findVisible,mc.findVisibleBlocks,mc.goTo,mc.mine,mc.collect,mc.craft,mc.equip,mc.place,mc.placeCraftingTable,mc.breakBlock,mc.attack,mc.follow,mc.explore,mc.jump,mc.stop,mc.lookAt,mc.inventory,mc.count. Установленные инструменты: ${JSON.stringify(this.toolNames())}. ${extra} Мир: ${JSON.stringify(this.world())} История: ${history} Игрок: ${user} Сообщение: ${msg}`;const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),CFG.aiTimeout);try{const r=await fetch(CFG.ollama,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:CFG.model,prompt,format:'json',stream:false,keep_alive:-1,options:{num_ctx:8192,num_predict:2400,temperature:.2}}),signal:ac.signal});const raw=await r.text();let d={};try{d=JSON.parse(raw)}catch(_){}if(!r.ok)throw Error(`Ollama HTTP ${r.status}: ${d.error||raw||'неизвестная ошибка'}`);return JSON.parse(d.response||'{}')}catch(e){if(e.name==='AbortError')throw Error('таймаут Ollama');throw e}finally{clearTimeout(timer)}}
async handle(user,msg){if(!msg?.trim())return;this.memory.history=this.memory.history||[];this.memory.history.push({user,message:msg,at:Date.now()});this.memory.history=this.memory.history.slice(-60);this.save();console.log(`[CHAT] ${user}: ${msg}`);if(/^!stop$/i.test(msg.trim())){this.stop();this.say('Остановился.');return}if(this.busy){this.say('Я сейчас выполняю предыдущую команду.');return}try{let o=await this.ai(user,msg),type=String(o?.type||'text').toLowerCase(),say=String(o?.say||'').trim();if(Array.isArray(o?.tools))for(const t of o.tools)try{await this.installTool(t.name,t.source)}catch(e){console.log('[TOOL ERROR]',e.message)}if(type!=='action'){this.say(say||'Не понял запрос. Уточни, пожалуйста.');return}if(say)this.say(say);let r=await this.run(o?.code,user);if(!r.ok&&r.missingTool){console.log('[AI] отсутствует инструмент:',r.missingTool);const retry=await this.ai(user,msg,`Ошибка MISSING_TOOL:${r.missingTool}. Сейчас создай именно этот инструмент в tools, затем верни полный исправленный action code. Не возвращай text.`);if(Array.isArray(retry?.tools))for(const t of retry.tools)try{await this.installTool(t.name,t.source)}catch(e){console.log('[TOOL ERROR]',e.message)}r=await this.run(retry?.code,user);if(!say&&retry?.say)this.say(String(retry.say).trim())}if(!r.ok)this.say('Ошибка действия: '+r.error);else if(!say)this.say('Готово.')}catch(e){console.error('[AI]',e);this.say('Ошибка AI: '+e.message)}}}
const bot=mineflayer.createBot({host:CFG.host,port:CFG.port,username:CFG.username,version:CFG.version});bot.loadPlugin(pathfinder);const agent=new Agent(bot)
bot.once('spawn',async()=>{try{bot.pathfinder.setMovements(new Movements(bot,minecraftData(bot.version)))}catch(e){console.log('[MOVEMENTS]',e.message)}console.log(`[BOT] ${CFG.username} подключён`);console.log('[AI] model:',CFG.model);console.log('[AI] Ollama:',CFG.ollama);console.log('[AI] timeout:',CFG.aiTimeout/1000,'sec');console.log('[AI] инструменты:',agent.toolNames().join(', ')||'нет');try{const r=await fetch(CFG.ollama,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:CFG.model,prompt:'OK',stream:false,keep_alive:-1,options:{num_ctx:1024,num_predict:4}})});console.log('[OLLAMA]',r.ok?'готова':'HTTP '+r.status)}catch(e){console.log('[OLLAMA]',e.message)}})
bot.on('chat',(u,m)=>{if(u!==bot.username)agent.handle(u,m)})
bot.on('whisper',(u,m)=>{if(u!==bot.username)agent.handle(u,m)})
bot.on('kicked',r=>console.log('[KICK]',r))
bot.on('error',e=>console.error('[BOT ERROR]',e.message||e))
bot.on('end',()=>console.log('[BOT] соединение закрыто'))
