const http=require('http');const fs=require('fs');const path=require('path');const {WebSocketServer}=require('ws');
const PORT=Number(process.env.PORT||8080),COLS=11,ROWS=15,TICK=90,MAX_ROOMS=100,MIN_PLAYERS=2,MAX_PLAYERS=4;
const SPAWNS=[{x:5,y:1,dx:0,dy:1},{x:1,y:7,dx:1,dy:0},{x:9,y:7,dx:-1,dy:0},{x:5,y:13,dx:0,dy:-1}];
const rooms=new Map(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let seq=1;
function code(){let s;do{s='';for(let i=0;i<6;i++)s+=alphabet[Math.floor(Math.random()*alphabet.length)]}while(rooms.has(s));return s}
function makeRoom(name,maxPlayers){const n=Math.max(MIN_PLAYERS,Math.min(MAX_PLAYERS,Number(maxPlayers)||4));const r={code:code(),name:name||'Неоновая арена',maxPlayers:n,players:Array(n).fill(null),segments:[],running:false,target:{x:5,y:7},scores:Array(n).fill(0),host:0};rooms.set(r.code,r);return r}
function send(ws,o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}function broadcast(r,o){r.players.forEach(p=>send(p?.ws,o))}
function lobby(r){return{type:'lobby',room:r.code,roomName:r.name,maxPlayers:r.maxPlayers,host:r.host,players:r.players.map((p,i)=>p?{id:i,name:p.name,host:i===r.host}:null)}}
function pubPlayers(r){return r.players.map(p=>p?{x:p.x,y:p.y,dir:p.dir,score:p.score,name:p.name}:null)}
function snapshot(r){return{type:'snapshot',players:pubPlayers(r),segments:r.segments.slice(-800),target:r.target}}
function start(r){r.segments=[];r.running=true;for(let i=0;i<r.players.length;i++){const p=r.players[i];if(!p)continue;const s=SPAWNS[i];p.x=s.x;p.y=s.y;p.dir={x:s.dx,y:s.dy};p.nextDir={x:s.dx,y:s.dy};p.alive=true;p.path=[{x:p.x,y:p.y}]}broadcast(r,{type:'start',room:r.code,playerCount:r.players.filter(Boolean).length,players:r.players.map((p,i)=>p?{id:i,name:p.name,host:i===r.host}:null)})}
function occupied(r,x,y,ignore){return r.players.some((p,i)=>p&&i!==ignore&&p.alive&&p.x===x&&p.y===y)||r.segments.some(s=>s.b.x===x&&s.b.y===y)}
function tick(r){if(!r.running)return;const moves=[];for(let i=0;i<r.players.length;i++){const p=r.players[i];if(!p||!p.alive)continue;const nd=p.nextDir;if(!(nd.x===-p.dir.x&&nd.y===-p.dir.y))p.dir=nd;const nx=p.x+p.dir.x,ny=p.y+p.dir.y;moves.push({i,p,nx,ny})}
 const losers=[];let winner=-1;for(const m of moves){const {i,nx,ny}=m;if(nx===r.target.x&&ny===r.target.y){winner=i;break}if(nx<0||nx>=COLS||ny<0||ny>=ROWS||occupied(r,nx,ny,i))losers.push(i)}
 if(winner>=0){r.scores[winner]++;broadcast(r,{type:'round',winner,scores:r.scores});r.running=false;setTimeout(()=>{if(r.players.filter(Boolean).length>=MIN_PLAYERS)start(r)},1400);return}
 for(const m of moves){if(losers.includes(m.i))continue;const p=m.p,a={x:p.x,y:p.y},b={x:m.nx,y:m.ny};r.segments.push({id:seq++,p:m.i,a,b});p.x=m.nx;p.y=m.ny;p.path.push(b)}
 if(losers.length){for(const i of losers)r.players[i].alive=false;const alive=r.players.filter(p=>p&&p.alive).length;if(alive<=1){const win=r.players.findIndex(p=>p&&p.alive);if(win>=0){r.scores[win]++;broadcast(r,{type:'round',winner:win,scores:r.scores})}r.running=false;setTimeout(()=>{if(r.players.filter(Boolean).length>=MIN_PLAYERS)start(r)},1400)}}
 broadcast(r,snapshot(r))}
function roomsList(){return[...rooms.values()].filter(r=>!r.running&&r.players.some(Boolean)).map(r=>({code:r.code,name:r.name,players:r.players.filter(Boolean).length,maxPlayers:r.maxPlayers}))}
const server=http.createServer((req,res)=>{const u=(req.url||'/').split('?')[0];if(u==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}))}if(u==='/rooms'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({rooms:roomsList()}))}if(u==='/'||u==='/index.html'){fs.readFile(path.join(__dirname,'..','index.html'),(e,d)=>{if(e){res.writeHead(500);return res.end('index.html not found')}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(d)});return}res.writeHead(404);res.end('Not found')});
const wss=new WebSocketServer({server});wss.on('connection',ws=>{let room=null,index=-1;send(ws,{type:'hello'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
 if(m.type==='create'){if(room)return;room=makeRoom(String(m.roomName||'Неоновая арена').trim().slice(0,26),m.maxPlayers);index=0;const name=String(m.name||'Игрок').trim().slice(0,18)||'Игрок';room.players[0]={ws,name,x:SPAWNS[0].x,y:SPAWNS[0].y,dir:{x:SPAWNS[0].dx,y:SPAWNS[0].dy},nextDir:{x:SPAWNS[0].dx,y:SPAWNS[0].dy},alive:true,score:0,path:[]};send(ws,{type:'created',room:room.code,player:0});send(ws,lobby(room));return}
 if(m.type==='join'){if(room)return;const r=rooms.get(String(m.room||'').toUpperCase());if(!r)return send(ws,{type:'error',message:'Комната не найдена'});if(r.running)return send(ws,{type:'error',message:'Раунд уже идёт'});if(r.players.filter(Boolean).length>=r.maxPlayers)return send(ws,{type:'error',message:'Комната заполнена'});room=r;index=r.players.findIndex(p=>!p);const name=String(m.name||'Игрок').trim().slice(0,18)||'Игрок';const s=SPAWNS[index];room.players[index]={ws,name,x:s.x,y:s.y,dir:{x:s.dx,y:s.dy},nextDir:{x:s.dx,y:s.dy},alive:true,score:0,path:[]};broadcast(room,lobby(room));return}
 if(!room||index<0)return;const p=room.players[index];if(!p)return;
 if(m.type==='start'){if(index!==room.host)return send(ws,{type:'error',message:'Запустить может только создатель'});if(room.players.filter(Boolean).length<MIN_PLAYERS)return send(ws,{type:'error',message:'Нужны минимум 2 игрока'});start(room)}
 else if(m.type==='direction'){let dx=Math.sign(Number(m.dx)||0),dy=Math.sign(Number(m.dy)||0);if(dx&&dy)return;if(dx||dy)p.nextDir={x:dx,y:dy}}
 });ws.on('close',()=>{if(!room||index<0)return;room.players[index]=null;room.running=false;room.segments=[];const next=room.players.findIndex(Boolean);if(index===room.host&&next>=0)room.host=next;if(next>=0)broadcast(room,lobby(room));else rooms.delete(room.code)})});
setInterval(()=>rooms.forEach(tick),TICK);server.listen(PORT,'0.0.0.0',()=>console.log('NEON LINES listening on '+PORT));
