const http=require('http');const fs=require('fs');const path=require('path');const os=require('os');const {WebSocketServer}=require('ws');
const PORT=Number(process.env.PORT||8080),WORLD={w:1000,h:700},TICK=50,SPEED=300,BULLET_SPEED=780,HIT_R=24,MAX_ROOMS=100;
const OBSTACLES=[{x:420,y:120,w:160,h:45},{x:420,y:535,w:160,h:45},{x:150,y:270,w:190,h:55},{x:660,y:375,w:190,h:55},{x:455,y:285,w:90,h:130},{x:55,y:90,w:90,h:90},{x:855,y:520,w:90,h:90}];
const WEAPONS={pistol:{damage:25,cooldown:260,mag:12,reload:900,spread:.015,pellets:1},smg:{damage:12,cooldown:85,mag:30,reload:1200,spread:.045,pellets:1},shotgun:{damage:10,cooldown:650,mag:6,reload:1500,spread:.18,pellets:7}};
const rooms=new Map(),alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let bulletSeq=1;
function roomCode(){let s='';do{s='';for(let i=0;i<6;i++)s+=alphabet[Math.floor(Math.random()*alphabet.length)]}while(rooms.has(s));return s}
function makeRoom(name,password){const code=roomCode(),r={code,name:name||'Комната',password:password||'',players:[null,null],bullets:[],scores:[0,0],running:false,lastTick:Date.now(),createdAt:Date.now()};rooms.set(code,r);return r}
function send(ws,o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}function broadcast(r,o){r.players.forEach(p=>send(p?.ws,o))}
function circleRect(x,y,rad,o){const cx=Math.max(o.x,Math.min(x,o.x+o.w)),cy=Math.max(o.y,Math.min(y,o.y+o.h));return Math.hypot(x-cx,y-cy)<rad}
function blocked(x,y,rad=22){return x<rad||x>WORLD.w-rad||y<rad||y>WORLD.h-rad||OBSTACLES.some(o=>circleRect(x,y,rad,o))}
function reset(r){if(!r.players[0]||!r.players[1])return;for(let i=0;i<2;i++){const p=r.players[i];p.x=i?750:250;p.y=350;p.hp=100;p.aim={x:i?-1:1,y:0};p.weapon='pistol';p.ammo=WEAPONS.pistol.mag;p.reloading=false;p.reloadUntil=0;p.lastShot=0}r.bullets=[];r.running=true}
function publicPlayer(p){return{x:p.x,y:p.y,hp:p.hp,score:p.score,name:p.name,weapon:p.weapon,ammo:p.ammo,mag:WEAPONS[p.weapon].mag,reloading:p.reloading,aim:p.aim}}
function snapshot(r){return{type:'snapshot',world:WORLD,obstacles:OBSTACLES,players:r.players.map(publicPlayer),bullets:r.bullets.map(b=>({id:b.id,x:b.x,y:b.y,owner:b.owner}))}}
function endRound(r,w){r.scores[w]++;r.players.forEach((p,i)=>{if(p)p.score=r.scores[i]});broadcast(r,{type:'round',winner:w,scores:r.scores});setTimeout(()=>{if(r.players[0]&&r.players[1])reset(r)},900)}
function reload(p){const now=Date.now(),gun=WEAPONS[p.weapon];if(!p.reloading&&p.ammo<gun.mag){p.reloading=true;p.reloadUntil=now+gun.reload}}
function fire(r,i){if(!r.running)return;const p=r.players[i],now=Date.now(),gun=WEAPONS[p.weapon];if(!p||p.reloading)return;if(p.ammo<=0)return reload(p);if(now-p.lastShot<gun.cooldown)return;p.lastShot=now;p.ammo--;let ax=p.aim.x,ay=p.aim.y,len=Math.hypot(ax,ay)||1;ax/=len;ay/=len;for(let k=0;k<gun.pellets;k++){const a=Math.atan2(ay,ax)+(Math.random()-.5)*gun.spread;const dx=Math.cos(a),dy=Math.sin(a);r.bullets.push({id:bulletSeq++,owner:i,x:p.x+dx*28,y:p.y+dy*28,vx:dx*BULLET_SPEED,vy:dy*BULLET_SPEED,life:1.2,damage:gun.damage})}}
function tick(r,dt){if(!r.running||!r.players[0]||!r.players[1])return;const now=Date.now();for(const p of r.players){if(p.reloading&&now>=p.reloadUntil){p.reloading=false;p.ammo=WEAPONS[p.weapon].mag}const ix=p.input.x,iy=p.input.y,l=Math.hypot(ix,iy)||1,s=Math.min(1,l),dx=ix/l*SPEED*dt*s,dy=iy/l*SPEED*dt*s;let nx=p.x+dx,ny=p.y+dy;if(!blocked(nx,p.y))p.x=nx;if(!blocked(p.x,ny))p.y=ny}
for(const b of r.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}for(let i=r.bullets.length-1;i>=0;i--){const b=r.bullets[i];if(b.life<=0||b.x<0||b.x>WORLD.w||b.y<0||b.y>WORLD.h||OBSTACLES.some(o=>circleRect(b.x,b.y,5,o))){r.bullets.splice(i,1);continue}const t=r.players[1-b.owner];if(t&&Math.hypot(b.x-t.x,b.y-t.y)<HIT_R){r.bullets.splice(i,1);t.hp-=b.damage;if(t.hp<=0){endRound(r,b.owner);return}}}}
function roomList(){return[...rooms.values()].filter(r=>r.players[0]&&!r.players[1]).map(r=>({code:r.code,name:r.name,host:r.players[0].name,locked:Boolean(r.password),players:1,maxPlayers:2})).sort((a,b)=>a.name.localeCompare(b.name,'ru'))}
const server=http.createServer((req,res)=>{const u=(req.url||'/').split('?')[0];if(u==='/health'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,rooms:rooms.size}))}if(u==='/rooms'){res.writeHead(200,{'content-type':'application/json','cache-control':'no-store'});return res.end(JSON.stringify({rooms:roomList()}))}if(u==='/'||u==='/index.html'){fs.readFile(path.join(__dirname,'..','index.html'),(e,d)=>{if(e){res.writeHead(500);return res.end('index.html not found')}res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(d)});return}res.writeHead(404);res.end('Not found')});
const wss=new WebSocketServer({server});wss.on('connection',ws=>{let room=null,index=-1;send(ws,{type:'hello'});ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='create'){if(room)return;if(rooms.size>=MAX_ROOMS)return send(ws,{type:'error',message:'Слишком много комнат. Попробуй позже.'});const name=String(m.name||'Игрок').trim().slice(0,20)||'Игрок',rn=String(m.roomName||'Неоновая арена').trim().slice(0,30)||'Неоновая арена',pw=String(m.password||'').slice(0,40);room=makeRoom(rn,pw);index=0;room.players[0]={ws,name,x:250,y:350,hp:100,score:0,input:{x:0,y:0},aim:{x:1,y:0},weapon:'pistol',ammo:12,reloading:false,reloadUntil:0,lastShot:0};return send(ws,{type:'created',room:room.code,roomName:room.name,locked:Boolean(room.password),player:0})}
if(m.type==='join'){if(room)return;const code=String(m.room||'').trim().toUpperCase(),r=rooms.get(code);if(!r)return send(ws,{type:'error',message:'Комната не найдена.'});if(r.players[0]&&r.players[1])return send(ws,{type:'error',message:'Комната уже заполнена.'});const pw=String(m.password||'').slice(0,40);if(r.password&&pw!==r.password)return send(ws,{type:'password_required',room:r.code,roomName:r.name});room=r;index=1;const name=String(m.name||'Игрок').trim().slice(0,20)||'Игрок';room.players[1]={ws,name,x:750,y:350,hp:100,score:0,input:{x:0,y:0},aim:{x:-1,y:0},weapon:'pistol',ammo:12,reloading:false,reloadUntil:0,lastShot:0};reset(room);for(let i=0;i<2;i++)send(room.players[i].ws,{type:'start',room:room.code,roomName:room.name,player:i,players:room.players.map(p=>({name:p.name}))});return}
if(!room||index<0)return;const p=room.players[index];if(m.type==='input'){p.input={x:Math.max(-1,Math.min(1,Number(m.x)||0)),y:Math.max(-1,Math.min(1,Number(m.y)||0))};const ax=Number(m.aimX),ay=Number(m.aimY),l=Math.hypot(ax,ay);if(Number.isFinite(ax)&&Number.isFinite(ay)&&l>.05)p.aim={x:ax/l,y:ay/l}}
else if(m.type==='shoot')fire(room,index);else if(m.type==='reload')reload(p);else if(m.type==='weapon'){const w=String(m.weapon);if(WEAPONS[w]){p.weapon=w;p.ammo=WEAPONS[w].mag;p.reloading=false}}});ws.on('close',()=>{if(!room||index<0)return;room.players[index]=null;room.running=false;room.bullets=[];const other=room.players[1-index];if(other)send(other.ws,{type:'opponent_left'});if(!room.players[0]&&!room.players[1])rooms.delete(room.code)})});
setInterval(()=>{const now=Date.now();for(const r of rooms.values()){const dt=Math.min(.1,(now-r.lastTick)/1000);r.lastTick=now;tick(r,dt);if(r.running)broadcast(r,snapshot(r))}},TICK);server.listen(PORT,'0.0.0.0',()=>console.log('NEON ARENA server listening on '+PORT));
